"use client";

import { FormEvent, useEffect, useState } from "react";
import { Dashboard } from "./dashboard";

const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
type Organization = { id: string; name: string; slug: string };
type DashboardData = Parameters<typeof Dashboard>[0]["data"];

export function App() {
  const [token, setToken] = useState<string | null>(null); const [organization, setOrganization] = useState<Organization | null>(null); const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState(""); const [createOpen, setCreateOpen] = useState(false);
  useEffect(() => { const stored = localStorage.getItem("statusforge_access_token"); if (stored) setToken(stored); }, []);
  useEffect(() => { if (token) loadOrganizations(token); }, [token]);
  useEffect(() => { if (token && organization) loadDashboard(token, organization.id); }, [token, organization]);
  async function loadOrganizations(accessToken: string) { try { const response = await fetch(`${apiUrl}/api/v1/organizations`, { headers: { Authorization: `Bearer ${accessToken}` } }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "Session expired"); setOrganization(body[0] || null); } catch (reason) { localStorage.removeItem("statusforge_access_token"); setToken(null); setError(reason instanceof Error ? reason.message : "Unable to load account"); } }
  async function loadDashboard(accessToken: string, id: string) { try { const response = await fetch(`${apiUrl}/api/v1/organizations/${id}/dashboard`, { headers: { Authorization: `Bearer ${accessToken}` } }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "Unable to load dashboard"); setData(body); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load dashboard"); } }
  async function authenticate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const register = form.get("mode") === "register"; try { const response = await fetch(`${apiUrl}/api/v1/auth/${register ? "register" : "login"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.get("email"), password: form.get("password"), ...(register ? { organization_name: form.get("organization") } : {}) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "Authentication failed"); localStorage.setItem("statusforge_access_token", body.access_token); setToken(body.access_token); } catch (reason) { setError(reason instanceof Error ? reason.message : "Authentication failed"); } }
  async function createMonitor(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!organization || !token) return; const form = new FormData(event.currentTarget); try { const response = await fetch(`${apiUrl}/api/v1/organizations/${organization.id}/monitors`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ name: form.get("name"), slug: String(form.get("name")).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""), type: form.get("type"), config: { url: form.get("url") } }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "Unable to create monitor"); setCreateOpen(false); await loadDashboard(token, organization.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to create monitor"); } }
  if (!token) return <AuthForm error={error} onSubmit={authenticate} />;
  if (!organization || !data) return <main className="loading">Loading StatusForge…</main>;
  return <><Dashboard data={data} onCreateMonitor={() => setCreateOpen(true)} />{createOpen && <div className="modal"><form className="dialog" onSubmit={createMonitor}><h2>Create monitor</h2><label>Name<input name="name" required minLength={2} /></label><label>Type<select name="type"><option value="HTTP">HTTP / HTTPS</option><option value="KEYWORD">Keyword</option><option value="JSON">JSON / API</option></select></label><label>URL<input name="url" required type="url" placeholder="https://api.example.com/health" /></label><div className="dialog-actions"><button type="button" className="quiet" onClick={() => setCreateOpen(false)}>Cancel</button><button className="primary">Create monitor</button></div></form></div>}{error && <p className="toast" role="alert">{error}</p>}</>;
}

function AuthForm({ error, onSubmit }: { error: string; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { const [register, setRegister] = useState(false); return <main className="auth"><form className="dialog" onSubmit={onSubmit}><div className="brand"><span className="brand-mark">S</span><span>StatusForge</span></div><h1>{register ? "Create your workspace" : "Welcome back"}</h1><p>Self-hosted reliability for your services.</p>{register && <label>Organization<input name="organization" required minLength={2} placeholder="Acme Engineering" /></label>}<label>Email<input name="email" required type="email" autoComplete="email" /></label><label>Password<input name="password" required type="password" minLength={12} autoComplete={register ? "new-password" : "current-password"} /></label><input name="mode" type="hidden" value={register ? "register" : "login"} />{error && <p className="form-error">{error}</p>}<button className="primary">{register ? "Create account" : "Sign in"}</button><button type="button" className="quiet" onClick={() => setRegister(!register)}>{register ? "Already have an account? Sign in" : "New here? Create an account"}</button></form></main>; }
