"use client";

type Summary = { total_monitors: number; monitors_up: number; monitors_down: number; active_incidents: number; uptime_percentage: number; average_response_time_ms: number | null };
type DashboardData = { summary: Summary; monitors: Array<{ id: string; name: string; type: string; status: string; last_checked_at: string | null }> };

export function Dashboard({ data, onCreateMonitor }: { data: DashboardData; onCreateMonitor: () => void }) {
  const cards = [["Monitors up", `${data.summary.monitors_up}/${data.summary.total_monitors}`, "Current service state"], ["Active incidents", String(data.summary.active_incidents), "Requires attention"], ["Average uptime", `${data.summary.uptime_percentage}%`, "Recorded checks"], ["Response time", data.summary.average_response_time_ms ? `${data.summary.average_response_time_ms} ms` : "—", "Average successful check"]];
  return <main className="shell theme-dark"><aside className="sidebar"><a className="brand" href="#overview"><span className="brand-mark">S</span><span>StatusForge</span></a><span className="workspace">OPERATIONS</span><nav>{["Overview", "Monitors", "Incidents", "Status Pages", "Maintenance", "Notifications", "Team", "Settings"].map((item) => <button className={item === "Overview" ? "nav-item active" : "nav-item"} key={item}>{item}</button>)}</nav></aside><section className="content" id="overview"><header className="topbar"><div><p className="eyebrow">OPERATIONS / OVERVIEW</p><h1>Reliability at a glance</h1></div><button className="primary" onClick={onCreateMonitor}>+ New monitor</button></header><div className={data.summary.monitors_down ? "notice warning" : "notice"}><span className="pulse" />{data.summary.monitors_down ? `${data.summary.monitors_down} monitor needs attention.` : "All monitored services are operational."}</div><section className="stats">{cards.map(([label, value, detail]) => <article className="metric" key={label}><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>)}</section><section className="panel"><div className="panel-heading"><div><h2>Monitors</h2><p>Live health from the monitoring engine.</p></div></div><div className="table-wrap"><table><thead><tr><th>Monitor</th><th>Status</th><th>Type</th><th>Last check</th></tr></thead><tbody>{data.monitors.length ? data.monitors.map((monitor) => <tr key={monitor.id}><td><strong>{monitor.name}</strong></td><td><Status status={monitor.status} /></td><td>{monitor.type}</td><td>{monitor.last_checked_at ? new Intl.DateTimeFormat(undefined, { timeStyle: "short" }).format(new Date(monitor.last_checked_at)) : "Awaiting first check"}</td></tr>) : <tr><td colSpan={4} className="empty-row">No monitors yet. Create your first monitor to begin.</td></tr>}</tbody></table></div></section></section></main>;
}

function Status({ status }: { status: string }) { return <span className={`status ${status.toLowerCase()}`}><i />{status}</span>; }
